FROM nginx:1.30-trixie

RUN rm -f /etc/nginx/conf.d/default.conf

COPY nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/ssl && chmod 700 /etc/nginx/ssl
COPY nginx/ssl/origin.crt /etc/nginx/ssl/origin.crt
COPY nginx/ssl/origin.key /etc/nginx/ssl/origin.key
RUN chmod 600 /etc/nginx/ssl/origin.key && chmod 644 /etc/nginx/ssl/origin.crt
EXPOSE 80 443
